### ISSUE TITLE
Update accountSelector component

### ISSUE THREAD

**Issue by samajammin** [SuperblocksHQ/ethereum-studio#208]
## Summary

A couple items to simplify & improve the UX of [this component](https://share.getcloudapp.com/E0uq2lKE)

- [ ] Clicking outside of dropdown/menu should exit this component
- [x] Remove the ["configure account" screen](https://share.getcloudapp.com/d5u0BEb6)

## Motivation

- Clicking outside of a menu to exit is a standard UX pattern
- The "configure account" screen is no longer necessary since there's only one network. For editing that name, we can have [the pencil icon ](https://share.getcloudapp.com/8LuJ5lq2) trigger the ability to directly edit the account name

## Describe alternatives you've considered
Instead of removing the "configure account" screen, we could just remove the "Configure the account for each network" section but I think it'd be a nice simplification to remove this modal entirely.

**Comment by samajammin** [comment]
@lovrobiljeskovic nice work removing the "configure account" screen but clicking outside of the menu still doesn't close it - any way we can fix that?

**Comment by samajammin** [comment]
Confirming this is still an issues.

**Comment by Spejbl** [comment]
Hey @samajammin this was because of the issue mentioned by Lovro, that it wasn't closing only when clicking on the iframe - the browser preview, as it doesn't have the same listeners as the main application. Only way I could think of solving this, was to wrap a fixed component around it. So it's more like a modal now. Would you mind to check out the PR for that? #247 Thanks
