### ISSUE TITLE
Add descriptive labeling to transactions tab

### ISSUE THREAD

**Issue by samajammin** [SuperblocksHQ/ethereum-studio#210]
## Summary

Let's replace the current title of each transaction with the function name & arguments.

## Motivation

Currently the deploy transaction is nice & descriptive (e.g. "Deploy Coin") but various interactions with the contract's function are vague (e.g. "Preview" & "Interact"). We should display the function & the arguments the user called on the contract in each transaction (e.g. "HelloWord update: Hello World!")

<img width="715" alt="Image 2020-03-10 at 10 36 37 AM" src="https://user-images.githubusercontent.com/8097623/76342046-26591480-62bb-11ea-8979-244948a852d1.png">

## Describe alternatives you've considered
Even deploying the function name without the arguments would be useful

## Additional context
None

**Comment by Spejbl** [comment]
Resolved in #220

@samajammin instead of adding the parameters inside the header as suggested it was put to the section underneath it, as seen in the picture below. There wasn't just enough room in the header when longer arguments were added.
![transaction](https://user-images.githubusercontent.com/17637244/77764388-88659800-7077-11ea-9003-93741f901dd0.png)
