### ISSUE TITLE
Fix "Support Ethereum Studio" popup

### ISSUE THREAD

**Issue by bashlund** [SuperblocksHQ/ethereum-studio#68]
## Environment/Browser
All

## Description
The popup is confusing.

- no diff in colour vs template popup makes it feel broken / unclear
- change "Support Ethereum Studio" to "Enable anonymous tracking?”

## Steps to reproduce
1. Open Studio in incognito to see the popup

## Expected result
Something which looks less confusing, since it overlaps the create new project popup.

## Actual result
I get the impression something is broken

## Reproducible
Yes

**Comment by samajammin** [comment]
### Current behavior

<img width="1439" alt="Image 2019-11-04 at 7 30 00 AM" src="https://user-images.githubusercontent.com/8097623/68133310-fd6fdf80-fed4-11e9-8616-194a69ea5d07.png">

### Potential solutions

@jjmstark & I spiked on a couple potential options here.

#### 1) overlay the tracking popup over the template popup if it's required to be the first interaction:

![image](https://user-images.githubusercontent.com/8097623/68133320-0496ed80-fed5-11e9-86ec-95781b8a7514.png)

Simple change but we don't think it's a good UX - the user receives no value before having to address this popup.

#### 2) decrease height of tracking popup & make it scrollable

e.g. https://share.getcloudapp.com/5zu5PdrG

 Another simple change but also not great UX - might be hard for the user to know they need to scroll in order to dismiss the popup.

#### 3) disable tracking by default for a user's first visit?
We think the optimal solution if it's possible. Could we set it up such that it only sends this popup on the second time the user loads the page i.e. its default no-tracking first time, and it waits until a reload (or a specific length of time). e.g. could we set a boolean in local storage? Or is that also considered tracking?

**Comment by samajammin** [comment]
Discussed w/ @javier-tarazaga - we're going to only display the tracking popup after a template is selected & a project is loaded.

**Comment by samajammin** [comment]
From @jjmstark re: change "Support Ethereum Studio" to "Enable anonymous tracking”

> ​​Reason this is important: when people read “Support X…” they will immediately think that it is asking for a donation, or asking for a subscription. Obviously that’s not what is happening here, but I don’t want the average user to be confused the first time they open it up.

**Comment by javier-tarazaga** [comment]
@samajammin @jjmstark this should be fixed in #80
