### ISSUE TITLE
Moving Contract file to different folder results in contract arguments lost

### ISSUE THREAD

**Issue by Spejbl** [SuperblocksHQ/ethereum-studio#93]
## Environment/Browser
Live/Firefox

## Description
When moving a Contract which has setup constructor arguments, for example the Hello World template, it loses those arguments upon moving contract to different folder.

## Steps to reproduce
1. Open `Hello World` template
2. Open Configure modal and check that there is 1 argument with value `Hello World!`
3. Try to move the Contract inside file system to the root folder by dragging it
4. Check Configure modal once again and there are 0 arguments now

## Expected result
Contract should preserve arguments upon moving this file

## Actual result
Contract loses all contract args upon moving it to different folder

## Reproducible
100%

**Comment by filippsen** [comment]
Perhaps the local environment is more permissive due to debug settings and extra guards, which allow opening up the broken _Configure_ ? In any case, there is an error when clicking _Configure_ under the reported circumstances.

Running on live environment, after _Step 3_ it is no longer possible to open the _Configure_ window due to the following error:
```
TypeError: r is undefined 2 contractConfig.reducer.ts:46:24
```

Moving the contract back to its original location (under `/contracts`), makes the _Configure_ work again. Arguments are **not** lost in the process.
